const A=document.querySelector("#app"),K="pma_v2";
const worlds={
number:{name:"Number Forest",icon:"🌳",need:0,levels:[
["n1","Gerbang Bilangan","🌿",[["18 + 27 = ...",["35","45","55","46"],1,"Pisahkan 27 menjadi 20 + 7."],["64 - 29 = ...",["35","43","45","34"],0,"Kurangi 30 lalu tambah 1."],["7 × 8 = ...",["48","54","56","64"],2,"Gunakan fakta perkalian."],["96 ÷ 12 = ...",["6","7","8","9"],2,"12 × berapa = 96?"]]],
["n2","Jembatan Pola","🌉",[["2, 5, 8, 11, ...",["12","13","14","15"],2,"Bertambah 3."],["40, 35, 30, 25, ...",["15","20","22","24"],1,"Berkurang 5."],["3, 6, 12, 24, ...",["27","36","42","48"],3,"Dikali 2."],["1, 4, 9, 16, ...",["20","24","25","32"],2,"Pola kuadrat."]]],
["n3","Gua Faktor","🪨",[["FPB 18 dan 24 = ...",["3","6","9","12"],1,"Cari faktor terbesar yang sama."],["KPK 6 dan 8 = ...",["12","18","24","48"],2,"Cari kelipatan terkecil yang sama."],["Bilangan prima adalah ...",["21","27","29","33"],2,"Hanya dua faktor."],["Faktor dari 36 adalah ...",["5","7","9","11"],2,"36 habis dibagi angka tersebut."]]],
["n4","Menara Negatif","🗼",[["-6 + 14 = ...",["-20","-8","8","20"],2,"Bergerak ke kanan."],["7 - 12 = ...",["-5","5","19","-19"],0,"Melewati nol."],["-4 × 6 = ...",["-24","24","-10","10"],0,"Negatif × positif."],["-36 ÷ -6 = ...",["-6","6","-30","30"],1,"Negatif ÷ negatif."]]],
["n5","Stone Golem","🗿",[["48 ÷ 6 + 7 × 3 = ...",["29","31","35","45"],0,"Bagi dan kali dahulu."],["30% dari 150 = ...",["35","40","45","50"],2,"10% adalah 15."],["-8 + 3 × 5 = ...",["-25","7","15","23"],1,"Perkalian dahulu."],["FPB 24 dan 36 = ...",["6","8","12","18"],2,"Faktor terbesar sama."]],true]},
fraction:{name:"Fraction Island",icon:"🏝️",need:10,levels:[
["f1","Pantai Pecahan","🥥",[["1/2 sama dengan ...",["2/3","2/4","3/4","1/4"],1,"Kalikan atas-bawah dengan 2."],["3/4 dalam desimal = ...",["0,25","0,50","0,75","1,25"],2,"3 ÷ 4."],["25% sama dengan ...",["1/2","1/3","1/4","3/4"],2,"25/100."],["Pecahan terbesar ...",["1/2","2/3","3/8","4/7"],1,"Bandingkan nilainya."]]],
["f2","Pizza Fraction","🍕",[["Pizza 8 potong, dimakan 3. Sisa ...",["3/8","5/8","5/3","8/5"],1,"Sisa 5 dari 8."],["1/4 + 2/4 = ...",["2/8","3/4","3/8","1/2"],1,"Jumlahkan pembilang."],["5/6 - 2/6 = ...",["3/6","3/12","7/6","2/3"],0,"Kurangkan pembilang."],["2/3 dari 12 = ...",["6","8","9","10"],1,"12 ÷ 3 × 2."]]],
["f3","Jembatan Pecahan","🌁",[["1/2 + 1/3 = ...",["2/5","5/6","2/6","1"],1,"Samakan penyebut."],["3/4 - 1/6 = ...",["5/12","7/12","2/10","1/2"],1,"Penyebut 12."],["2/5 × 15 = ...",["5","6","8","10"],1,"15 ÷ 5 × 2."],["3/4 ÷ 1/2 = ...",["3/8","2/3","3/2","1"],2,"Kalikan kebalikan."]]],
["f4","Pasar Diskon","🛍️",[["Rp120.000 diskon 25%. Harga ...",["Rp80.000","Rp90.000","Rp95.000","Rp100.000"],1,"Diskon Rp30.000."],["40% dari bilangan = 32. Bilangan ...",["64","72","80","96"],2,"32 ÷ 0,4."],["60 naik menjadi 75. Kenaikan ...",["15%","20%","25%","30%"],2,"Naik 15 dari 60."],["Diskon 20%, harga Rp160.000. Awal ...",["Rp180.000","Rp190.000","Rp200.000","Rp220.000"],2,"160.000 adalah 80%."]]],
["f5","Captain Percent","🏴‍☠️",[["3/5 + 1/4 = ...",["4/9","17/20","4/20","7/10"],1,"Penyebut 20."],["15% dari 240 = ...",["24","30","36","40"],2,"10%=24, 5%=12."],["0,375 = ...",["3/8","3/5","5/8","7/8"],0,"375/1000."],["Rp250.000 naik 12%. Jadi ...",["Rp270.000","Rp275.000","Rp280.000","Rp290.000"],2,"Naik Rp30.000."]],true]]}};
const shopItems=[["🎩","Wizard Hat",250],["🐱","Math Cat",450],["🦊","Number Fox",650],["👑","Crystal Crown",900],["🐲","Mini Dragon",1200]];
let S=JSON.parse(localStorage.getItem(K)||"null"),selected="🧑‍🚀";
const save=()=>localStorage.setItem(K,JSON.stringify(S)),stars=()=>Object.values(S.stars||{}).reduce((a,b)=>a+b,0),st=n=>"⭐".repeat(n)+"☆".repeat(3-n);
function top(){return `<div class=top><div class=brand>∑ <span>PakKom Math Adventure</span></div><div class=stats><b class=pill>${S.avatar}</b><b class=pill>⭐ ${stars()}</b><b class=pill>⚡ ${S.xp}</b><b class=pill>🪙 ${S.coin}</b></div></div>`}
function tabs(a){return `<div class=tabs>${[["home","🗺️ Adventure"],["shop","🛍️ Shop"],["ach","🏅 Achievement"],["teacher","👩‍🏫 Demo Guru"]].map(x=>`<button class="btn ${a==x[0]?"dark":"soft"}" data-tab=${x[0]}>${x[1]}</button>`).join("")}</div>`}
function bind(){document.querySelectorAll("[data-tab]").forEach(b=>b.onclick=()=>({home,shop,ach,teacher}[b.dataset.tab])())}
function login(){let av=["🧑‍🚀","🧙","🥷","🦸","🧑‍🔬","🧝"];A.innerHTML=`<div class=login><div class=card><h1>∑ Math Adventure v2</h1><p>The Lost Math Crystals</p><label>NIS</label><input id=nis><label>Nama</label><input id=nm><label>Kelas</label><select id=cl>${["7A","7B","7C","7D","7E","7F","7G","7H","7I","8A","8B","8C","8D","8E","8F","8G","8H","8I","9A","9B","9C","9D","9E","9F","9G","9H","9I"].map(x=>`<option>${x}</option>`)}</select><label>Avatar</label><div class=avatars>${av.map((x,i)=>`<button class="av ${i?"":"sel"}">${x}</button>`).join("")}</div><br><button id=go class="btn dark">Mulai Petualangan →</button><p class=small>Demo lokal. NIS disiapkan untuk Firebase.</p></div></div>`;document.querySelectorAll(".av").forEach(b=>b.onclick=()=>{selected=b.textContent;document.querySelectorAll(".av").forEach(x=>x.classList.remove("sel"));b.classList.add("sel")});go.onclick=()=>{if(!nis.value||!nm.value)return alert("Isi NIS dan nama.");S={nis:nis.value,name:nm.value,cls:cl.value,avatar:selected,xp:0,coin:0,stars:{},done:{},items:[],badges:[]};save();home()}}
function home(){A.innerHTML=`<div class=wrap>${top()}${tabs("home")}<div class=hero><small>CHAPTER 1 • THE LOST MATH CRYSTALS</small><h1>${S.avatar} Halo, ${S.name}!</h1><p>Jelajahi dua dunia, kumpulkan bintang, kalahkan boss, dan rebut kembali Kristal Matematika.</p></div><div class=grid>${Object.entries(worlds).map(([k,w])=>`<div class="card c6 world"><div class=icon>${w.icon}</div><small>${stars()>=w.need?"DUNIA TERBUKA":"🔒 BUTUH "+w.need+" BINTANG"}</small><h2>${w.name}</h2><p>${k=="number"?"Operasi, pola, faktor dan bilangan negatif.":"Pecahan, desimal, persen dan diskon."}</p><button data-world=${k} class="btn green" ${stars()<w.need?"disabled":""}>Jelajahi →</button></div>`).join("")}<div class="card c8"><h2>🎯 Daily Quest</h2><p>⭐ Raih 3 bintang &nbsp; • &nbsp; 🔥 Streak 3 &nbsp; • &nbsp; 🪙 Kumpulkan 100 koin</p></div><div class="card c4"><h2>🏫 Class Boss</h2><p>Ancient Dragon</p><div class=progress><span style="width:38%"></span></div><p class=small>Preview untuk mode kelas online.</p></div></div></div>`;bind();document.querySelectorAll("[data-world]").forEach(b=>b.onclick=()=>map(b.dataset.world))}
function map(k){let w=worlds[k];A.innerHTML=`<div class=wrap>${top()}${tabs("home")}<button class="btn soft" id=back>← Semua Dunia</button><h1>${w.icon} ${w.name}</h1><div class=card><div class=map>${w.levels.map((l,i)=>`<div><button data-level=${l[0]} class="node ${S.done[l[0]]?"done":""} ${l[4]?"boss":""}" ${(i&& !S.done[w.levels[i-1][0]])?"disabled":""}><div>${l[2]}</div><small>${l[4]?"BOSS":"LEVEL "+(i+1)}</small></button><div class=stars>${S.done[l[0]]?st(S.stars[l[0]]):"Siap"}</div></div>${i<w.levels.length-1?"<div class=line></div>":""}`).join("")}</div></div></div>`;bind();back.onclick=home;document.querySelectorAll("[data-level]").forEach(b=>b.onclick=()=>play(k,b.dataset.level))}
function play(k,id){let l=worlds[k].levels.find(x=>x[0]==id),i=0,correct=0,hp=100,bhp=l[4]?300:0,dmg=40;A.innerHTML=`<div class=wrap>${top()}<button id=quit class="btn soft">← Peta</button><h1>${l[2]} ${l[1]}</h1><div id=stage></div></div>`;quit.onclick=()=>map(k);function show(){if(l[4]&&bhp<=0)return finish();if(i>=l[3].length){if(l[4])i=0;else return finish()}let q=l[3][i];stage.innerHTML=`${l[4]?`<div class=battle><div class=card>${S.avatar} <b>${S.name}</b><div class=hp><span style="width:${hp}%"></span></div>HP ${hp}</div><div class=card>${l[2]} <b>${l[1]}</b><div class=hp><span style="width:${Math.max(0,bhp/3)}%"></span></div>HP ${Math.max(0,bhp)}</div></div><div class=attacks>${[[30,"⚡ Quick"],[55,"🔥 Power"],[80,"💥 Ultimate"]].map(x=>`<button data-d=${x[0]} class="btn attack soft">${x[1]} • ${x[0]}</button>`).join("")}</div>`:""}<div class=card><span class=pill>Soal ${i+1}/${l[3].length}</span><div class=question>${q[0]}</div><div class=choices>${q[1].map((x,j)=>`<button class=choice data-c=${j}>${x}</button>`).join("")}</div><div id=fb></div></div>`;document.querySelectorAll("[data-d]").forEach(b=>b.onclick=()=>{dmg=+b.dataset.d;document.querySelectorAll(".attack").forEach(x=>x.classList.remove("sel"));b.classList.add("sel")});document.querySelectorAll("[data-c]").forEach(b=>b.onclick=()=>{let ok=+b.dataset.c==q[2];document.querySelectorAll("[data-c]").forEach(x=>x.disabled=true);b.classList.add(ok?"ok":"no");if(ok){correct++;if(l[4])bhp-=dmg}else{if(l[4])hp-=15;document.querySelectorAll("[data-c]")[q[2]].classList.add("ok")}fb.innerHTML=`<div class=feedback>${ok?"✅ Benar!":"💡 "+q[3]}</div><button id=next class="btn green">Lanjut →</button>`;next.onclick=()=>{if(hp<=0)return play(k,id);i++;show()}})}function finish(){let r=correct/l[3].length,n=r>=.9?3:r>=.75?2:r>=.5?1:0;if(l[4])n=Math.max(n,2);let first=!S.done[id];S.done[id]=true;S.stars[id]=Math.max(S.stars[id]||0,n);if(first){S.xp+=l[4]?250:80;S.coin+=l[4]?120:35}if(l[4]&&!S.badges.includes("🐲 Boss Hunter"))S.badges.push("🐲 Boss Hunter");save();stage.innerHTML=`<div class=card style="text-align:center"><div class=icon>${l[4]?"💎":"🏆"}</div><h1>Petualangan berhasil!</h1><h2>${st(n)}</h2><p>Benar ${correct}/${l[3].length}</p><button id=tomap class="btn dark">Kembali ke Peta</button></div>`;tomap.onclick=()=>map(k)}show()}
function shop(){A.innerHTML=`<div class=wrap>${top()}${tabs("shop")}<h1>🛍️ Adventure Shop</h1><div class=shop>${shopItems.map((x,i)=>`<div class="card item"><div class=icon>${x[0]}</div><h3>${x[1]}</h3><p>🪙 ${x[2]}</p><button data-buy=${i} class="btn gold" ${S.items.includes(i)?"disabled":""}>${S.items.includes(i)?"✓ Dimiliki":"Beli"}</button></div>`).join("")}</div></div>`;bind();document.querySelectorAll("[data-buy]").forEach(b=>b.onclick=()=>{let i=+b.dataset.buy;if(S.coin<shopItems[i][2])return alert("Koin belum cukup.");S.coin-=shopItems[i][2];S.items.push(i);save();shop()})}
function ach(){A.innerHTML=`<div class=wrap>${top()}${tabs("ach")}<div class=grid><div class="card c4" style="text-align:center"><div class=icon>${S.avatar}</div><h2>${S.name}</h2><p>NIS ${S.nis} • ${S.cls}</p><button id=reset class="btn soft">Reset Demo</button></div><div class="card c8"><h2>🏅 Achievement</h2><p>${S.badges.length?S.badges.join(" &nbsp; "):"Belum ada badge."}</p><h2>🎒 Koleksi</h2><p>${S.items.length?S.items.map(i=>shopItems[i][0]+" "+shopItems[i][1]).join(" &nbsp; "):"Belum ada item."}</p></div></div></div>`;bind();reset.onclick=()=>{if(confirm("Hapus progress?")){localStorage.removeItem(K);S=null;login()}}}
function teacher(){A.innerHTML=`<div class=wrap>${top()}${tabs("teacher")}<div class=hero><small>TEACHER COMMAND CENTER • PREVIEW</small><h1>👩‍🏫 Progress Kelas</h1><p>Dashboard ini adalah rancangan untuk versi Firebase, sehingga guru nanti dapat melihat seluruh siswa.</p></div><div class=grid><div class="card c4"><small>SISWA DEMO</small><h1>1</h1></div><div class="card c4"><small>TOTAL BINTANG</small><h1>⭐ ${stars()}</h1></div><div class="card c4"><small>XP</small><h1>⚡ ${S.xp}</h1></div><div class="card c8"><h2>Analisis</h2><p><b>${S.name}</b> • ${S.cls}</p><p>Number Forest: ${worlds.number.levels.filter(x=>S.done[x[0]]).length}/5 level</p><p>Fraction Island: ${worlds.fraction.levels.filter(x=>S.done[x[0]]).length}/5 level</p></div><div class="card c4"><h2>🐉 Class Boss</h2><div class=progress><span style="width:38%"></span></div><p class=small>Kontribusi kelas akan aktif setelah Firestore.</p></div></div></div>`;bind()}
S?home():login();